/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ifpb.visao;

import com.ifpb.controle.ComandaDao;
import com.ifpb.controle.ComandaDaoCollection;
import com.ifpb.controle.PedidoDao;
import com.ifpb.controle.PedidoDaoCollection;
import com.ifpb.modelo.Comanda;
import com.ifpb.modelo.Pedido;
import java.io.IOException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juvenal Carlos Cardo
 */
public class GerenciarMesa extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarMesa
     */
     ComandaDao daoComanda;
     PedidoDao daoPedidos;
    public GerenciarMesa() throws IOException {
        initComponents();
        daoComanda = new ComandaDaoCollection();
        daoPedidos = new PedidoDaoCollection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        controleMesa = new javax.swing.JSpinner();
        ButtonNovaComanda = new javax.swing.JButton();
        ButtonVerPedidos = new javax.swing.JButton();
        ButtonFazerPedidos = new javax.swing.JButton();
        ButtonEncerraComanda = new javax.swing.JButton();
        ButtonVoltarTelaPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mesa:");

        ButtonNovaComanda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonNovaComanda.setText("Nova comanda");
        ButtonNovaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovaComandaActionPerformed(evt);
            }
        });

        ButtonVerPedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonVerPedidos.setText("Ver pedidos");
        ButtonVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerPedidosActionPerformed(evt);
            }
        });

        ButtonFazerPedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonFazerPedidos.setText("Fazer pedidos");
        ButtonFazerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFazerPedidosActionPerformed(evt);
            }
        });

        ButtonEncerraComanda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonEncerraComanda.setText("Encerrar comanda");
        ButtonEncerraComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEncerraComandaActionPerformed(evt);
            }
        });

        ButtonVoltarTelaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonVoltarTelaPrincipal.setText("Volta Tela principal");
        ButtonVoltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarTelaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controleMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonNovaComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonVerPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonFazerPedidos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonEncerraComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonVoltarTelaPrincipal)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controleMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNovaComanda)
                    .addComponent(ButtonVerPedidos)
                    .addComponent(ButtonFazerPedidos))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEncerraComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonVoltarTelaPrincipal))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gerênciar Mesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonFazerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFazerPedidosActionPerformed
        // TODO add your handling code here:
        int mesa = (int) controleMesa.getValue(); //Pega o valor do root e atribui
        if(daoComanda.temComanda(mesa)){
            this.dispose();
            try {
                new FazerPedido(mesa).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(GerenciarMesa.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else JOptionPane.showMessageDialog(rootPane, "Não existe uma comanda aberta para essa mesa!", null, JOptionPane.WARNING_MESSAGE, null);
    }//GEN-LAST:event_ButtonFazerPedidosActionPerformed

    private void ButtonVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerPedidosActionPerformed
        // TODO add your handling code here:
         int mesa = (int) controleMesa.getValue();
         if(daoComanda.temComanda(mesa)){
             this.dispose();
             try {
                 new VerPedidos(mesa).setVisible(true);
             } catch (IOException ex) {
                 Logger.getLogger(GerenciarMesa.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else JOptionPane.showMessageDialog(rootPane, "Não existe uma comanda aberta para essa mesa!", null, JOptionPane.WARNING_MESSAGE, null);
    }//GEN-LAST:event_ButtonVerPedidosActionPerformed

    private void ButtonNovaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovaComandaActionPerformed
        // TODO add your handling code here:
        int mesa = (int) controleMesa.getValue();
        Set<Pedido> pedido = null;
        Comanda comanda = new Comanda(pedido,mesa);
        comanda.setNumMesa(mesa);
        
        if(daoComanda.salvarComanda(comanda)){
            JOptionPane.showMessageDialog(rootPane, "Nova comanda para a mesa " + mesa);
            this.dispose();
            new TelaPrincipal().setVisible(true);
        }else JOptionPane.showMessageDialog(rootPane, "Já existe uma comanda aberta para essa mesa!", null, JOptionPane.WARNING_MESSAGE, null);
    }//GEN-LAST:event_ButtonNovaComandaActionPerformed

    private void ButtonEncerraComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEncerraComandaActionPerformed
        // TODO add your handling code here:
        int mesa = (int)controleMesa.getValue();
        double Total = 0;
        Set<Pedido> pedidos = daoPedidos.getPedidoMesa(mesa);
        if(daoComanda.deletaComanda(mesa)){
            Total = daoPedidos.valorTotal(mesa);
            JOptionPane.showMessageDialog(rootPane, "Comanda encerrada. Total R$"+Total, null, JOptionPane.PLAIN_MESSAGE, null);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhuma comanda aberta para essa mesa", null, JOptionPane.WARNING_MESSAGE, null);
        }
    }//GEN-LAST:event_ButtonEncerraComandaActionPerformed

    private void ButtonVoltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarTelaPrincipalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_ButtonVoltarTelaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GerenciarMesa().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GerenciarMesa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEncerraComanda;
    private javax.swing.JButton ButtonFazerPedidos;
    private javax.swing.JButton ButtonNovaComanda;
    private javax.swing.JButton ButtonVerPedidos;
    private javax.swing.JButton ButtonVoltarTelaPrincipal;
    private javax.swing.JSpinner controleMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
